# config file version
apiVersion: 1

# list of datasources to insert/update
# available in the database
datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgres.:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: 'postgres'
    jsonData:
      sslmode: 'disable'